name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun ci
      - run: bun run build
      - run: bun run test
        env:
          CI: true
          HIFI_ARL: ${{ secrets.HIFI_ARL }}
